### ISSUE TITLE
SQLSTATE[HY000] [2002] php_network_getaddresses when migrate

### ISSUE THREAD

**Issue by franmadj** [neoighodaro/laravel-docker#4]
when php artisan migrate I get:

> Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)

using mysql this is my .env:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

and this the docker-compose.yml:
```
version: '3'
services:
  webapp:
    env_file: .env
    restart: unless-stopped
    build:
      context: ./web
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_HASH=${COMPOSER_HASH}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
        - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
    ports:
      - '8888:80'
    volumes:
      - ./web/src:/var/www
      - ./logs/web:/var/www/storage/logs
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    env_file: .env
    restart: unless-stopped
    build: ./databases/mysql
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./storage/mysql:/var/lib/mysql
      - ./databases/mysql/conf.d:/etc/mysql/conf.d
```
Thanks.
